version: '3'

services:
  nginx1:
    image: nginx:latest
    ports:
      - "8001:80"
  


  nginx3:
    image: nginx:latest
    ports:
      - "8003:80"

  nginx4:
    image: nginx:latest
    ports:
      - "8004:80"
