version: '3'
services:
  nginx1:
    image: nginx:latest

  nginx3:
    image: nginx:latest
    ports:
      - "8003:80"
  nginx3:
    image: nginx:latest
   

  nginx4:
    image: nginx:latest
    ports:
      - "8004:80"
  nginx5:
    image: nginx:latest

      - "8005:80"
  nginx4:
    image: nginx:latest
    ports:
      - "8004:80"

  nginx5:
    image: nginx:latest


  nginx6:
    

  nginx7:
    image: nginx:latest
    ports:
      - "8007:80"

  nginx8:
    image: nginx:latest
    ports:
      - "8008:80"

  nginx9:
    image: nginx:latest
    ports:
      - "8009:80"

