
version: '3.5'
services:
  nginx1:
    image: nginx:latest
    ports:
      - "8001:80"
  
 # nginx2:
    image: nginx:latest
    ports:
      - "8002:80"
  nginx3:
    ports:
      - "8003:80"
  nginx4:
    image: nginx:latest
    ports:
      - "8004:80"
  nginx5:
    image: nginx:latest
    ports:
      - "8005:80"
  nginx4:
    image: nginx:latest
    ports:
      - "8004:80"

  nginx5:
    image: nginx:latest

  nginx6:
    image: nginx:latest
    ports:
      - "8006:80"

  nginx7:
    image: nginx:latest
    ports:
      - "8007:80"

  nginx8:
    image: nginx:latest
    ports:
      - "8008:80"

  nginx9:
    image: nginx:latest
    ports:
      - "8009:80"

