
version: '3.5'
services:
  nginx1:
    image: nginx:latest
    ports:
      - "8001:80"


  nginx6:
    image: nginx:latest
    ports:
      - "8006:80"
  nginx7:
    image: nginx:latest
    ports:
      - "8007:80"
  nginx8:
    image: nginx:latest
    ports:
      - "8008:80"
  nginx9:
    image: nginx:latest
    ports:
      - "8009:80"
