
version: '3.8'

    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      MYSQL_DATA
      kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:BASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
     image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      MYSQL_DATA
      kind: Deployment 
      

networks:
  my_network:

volumes:
  db_data:
apiVersion: apps/v1

    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-container
        image: nginx:
        kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
        - containerPort: 80
