apiVersion: apps/v1
kind: Deployment
metadata:
  name: christelle-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: christelle-app
  template:
    metadata:
      labels:
        app: christelle-app
    spec:
      containers:
      - name: christelle-container
        image: nginx:latest
        ports:
        - containerPort: 80

