apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/5 * * * *"   # Cron schedule in standard cron format (every 5 minutes)
  jobTemplate:
    spec:
      template:
        metadata:
          name: example-job
        spec:
          containers:
          - name: example-container
            image: busybox
            command: ["/bin/sh", "-c", "date; echo Hello from the Kubernetes cluster"]
          restartPolicy: OnFailure

